### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by nitoa1** [luchobenitez/monda-guasu#1]
Buenas Mauricio, visto que en tu diccionario de datos hay mas columnas que en los 2 csv, betdp.csv y epassam.csv.

Esto estarán agregando en las horas siguientes?, hay mas datos?

Saludos y felicitaciones por el trabajo

**Comment by luchobenitez** [comment]
esos dos csv no son oficiales.
lo oficial esta en /base.

**Comment by luchobenitez** [comment]
voy a cerrar el ticket. fue solo una consulta sobre los datos.

**Comment by nitoa1** [comment]
gracias Lucho
